replicaCount: 1

image:
  repository: ghcr.io/minakovmax86/fastapi-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  - name: MLFLOW_S3_ENDPOINT_URL
    value: https://storage.yandexcloud.net
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: mlflow-secrets
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: mlflow-secrets
        key: AWS_SECRET_ACCESS_KEY
