replicaCount: 1

containerPort: 9090

image:
  repository: ghcr.io/minakovmax/fastapi-app
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - name: ghcr-auth

service:
  type: NodePort
  port: 80
  targetPort: 9090
  nodePort: 31090 # новый NodePort

env:
  - name: MLFLOW_S3_ENDPOINT_URL
    value: https://storage.yandexcloud.net
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: mlflow-secrets
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: mlflow-secrets
        key: AWS_SECRET_ACCESS_KEY
