replicaCount: 1

image:
  repository: ghcr.io/mlflow/mlflow
  tag: v2.22.1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

backendStore:
  database:
    type: postgresql
    host: ${PG_HOST}
    port: 6432
    database: mlflow
    user: mlflow
    password: ${PG_PASSWORD_URL_ENCODED}
    sslmode: require

artifactRoot:
  type: s3
  path: "s3://${BUCKET_NAME}/artifacts"

minio:
  enabled: false

externalS3:
  enabled: true
  bucket: "${BUCKET_NAME}"
  endpoint: "https://storage.yandexcloud.net"
  secretName: mlflow-s3-credentials
  accessKeyField: AWS_ACCESS_KEY_ID
  secretKeyField: AWS_SECRET_ACCESS_KEY
  region: "ru-central1"
  useVirtualHost: true
