replicaCount: 1

image:
  repository: ghcr.io/minakovmax/mlflow
  tag: v2.22.1
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

service:
  type: LoadBalancer
  port: 8080

postgresql:
  enabled: false

# Настройка backendStore для PostgreSQL
backendStore:
  postgres:
    enabled: true
    host: ${PG_HOST}
    port: 6432
    database: mlflow
    user: mlflow
    password: ${PG_PASSWORD_URL_ENCODED}
    driver: "psycopg2"

# Настройка artifactRoot для S3-хранилища
artifactRoot:
  s3:
    enabled: true
    bucket: "${BUCKET_NAME}"
    awsAccessKeyId: "${AWS_ACCESS_KEY_ID}"
    awsSecretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
    # endpointUrl параметр не поддерживается напрямую, но можно задать через переменные окружения

# Переменные окружения для нестандартного S3 (Yandex)
extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: "https://storage.yandexcloud.net"
  MLFLOW_S3_USE_VIRTUAL_HOST: "true"
