replicaCount: 1

image:
  repository: bitnami/mlflow
  tag: "2.10.1-debian-11-r0"

service:
  type: LoadBalancer
  port: 8080

env:
  backendStoreUri: "postgresql://mlflow:T3rr%40Form123%21@rc1a-4mp95d2gbehp61lc.mdb.yandexcloud.net:6432/mlflow"
  artifactRoot: "s3://ml-models-07bb6899/artifacts"
  s3EndpointUrl: "https://storage.yandexcloud.net"
  useSecret: true
  secretName: mlflow-s3-credentials
