replicaCount: 1

image:
  repository: bitnami/mlflow
  tag: "2.10.1-debian-11-r0"

service:
  type: LoadBalancer
  port: 8080

env:
  backendStoreUri: "postgresql://mlflow:${PG_PASSWORD_URL_ENCODED}@${PG_HOST}:6432/mlflow"
  artifactRoot: "s3://${BUCKET_NAME}/artifacts"
  s3EndpointUrl: "https://storage.yandexcloud.net"
  useSecret: true
  secretName: mlflow-s3-credentials
