apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
          command: ["mlflow"]          
          args:
            - "server"
            - "--backend-store-uri=$(BACKEND_STORE_URI)"
            - "--default-artifact-root=$(ARTIFACT_ROOT)"
            - "--host=0.0.0.0"
            - "--port=8080"
          env:
            - name: BACKEND_STORE_URI
              value: "{{ .Values.env.backendStoreUri }}"
            - name: ARTIFACT_ROOT
              value: "{{ .Values.env.artifactRoot }}"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "{{ .Values.env.s3EndpointUrl }}"
          {{- if .Values.env.useSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.env.secretName }}
          {{- end }}