name: Build & Push FastAPI

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ghcr.io

    - name: Build and Push Docker image
      run: |
        IMAGE=ghcr.io/minakovmax/fastapi-app:latest
        docker build -t $IMAGE ./app
        docker push $IMAGE

        - name: Install Yandex Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
      
    - name: Set up Yandex CLI and kubeconfig
      run: |
          echo "${{ secrets.YC_SA_KEY_JSON }}" > key.json
          yc config set service-account-key key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          yc container registry configure-docker
          yc managed-kubernetes cluster get-credentials ${{ secrets.YC_K8S_CLUSTER_ID }} --zone ${{ secrets.YC_ZONE }} --external

    - name: Create or update Kubernetes secret for MLflow
      run: |
        kubectl create secret generic mlflow-secrets \
          --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.3

    - name: Deploy with Helm
      run: |
        helm upgrade --install fastapi charts/fastapi \
          --set image.repository=ghcr.io/${{ github.repository_owner }}/fastapi-app \
          --set image.tag=latest