name: Deploy MLflow to Kubernetes

on:
  push:
    branches: [main]
  workflow_dispatch: # Для ручного запуска через UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PG_PASSWORD_URL_ENCODED: ${{ secrets.PG_PASSWORD_URL_ENCODED }}
      PG_HOST: ${{ secrets.PG_HOST }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.28.0"
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      
    - name: Configure kubeconfig
      shell: bash
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

    - name: Create Docker Registry Secret in Kubernetes
      shell: bash
      run: |
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username="${DOCKER_USERNAME}" \
          --docker-password="${DOCKER_PASSWORD}" \
          --docker-email=minakovmax86@gmail.com \
          --dry-run=client -o yaml | kubectl apply -f -
      # Если меняешь имя секрета — поменяй и в values.yaml!

    - name: Create S3 credentials secret
      shell: bash
      run: |
        kubectl create secret generic mlflow-s3-credentials \
          --from-literal=AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
          --from-literal=AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
          --dry-run=client -o yaml | kubectl apply -f -
    
    - name: Export env and render values.yaml
      shell: bash
      run: |
        export PG_PASSWORD_URL_ENCODED
        export PG_HOST
        export BUCKET_NAME
        export AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY
        envsubst < charts/mlflow/values-template.yaml > charts/mlflow/values.yaml
        cat charts/mlflow/values.yaml  # Для отладки
        
    - name: Clean up old mlflow pods
      shell: bash
      run: |
        set +e
        kubectl get pods | grep mlflow | grep -E 'Completed|Error|CrashLoopBackOff' | awk '{print $1}' | xargs -r kubectl delete pod || true

    - name: Helm upgrade MLflow
      shell: bash
      run: |
        helm repo add community-charts https://community-charts.github.io/helm-charts
        helm repo update
        helm upgrade --install mlflow-release community-charts/mlflow \
          -f charts/mlflow/values.yaml \
          --wait --timeout 10m0s