name: Deploy MLflow to Kubernetes

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PG_PASSWORD_URL_ENCODED: ${{ secrets.PG_PASSWORD_URL_ENCODED }}
      PG_HOST: ${{ secrets.PG_HOST }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.28.0" # можешь обновить по необходимости

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Export env and render values.yaml
        run: |
          set -a
          source infra/.env
          envsubst < charts/mlflow/values-template.yaml > charts/mlflow/values.yaml
          set +a

      - name: Helm upgrade MLflow
        run: |
          helm upgrade --install mlflow ./charts/mlflow -f charts/mlflow/values.yaml
